# Generated by Django 4.2.1 on 2023-05-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_delete_useravatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(default=None, null=True),
        ),
    ]
