# Generated by Django 4.2.1 on 2023-05-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
