# Generated by Django 4.2.1 on 2023-06-01 07:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
