# Generated by Django 4.2.1 on 2023-06-02 13:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_watchlist_favorites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="favorites",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(max_length=10, null=True),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
