from django.conf import settings
from django.conf.urls.static import static

from django.urls import path
from . import views

app_name = 'cryptocurrency'

print(settings.STATIC_ROOT)
urlpatterns = [
                  path('', views.home, name='home'),
                  path('rates/', views.rates, name='rates'),
                  path('rates/load_all/', views.load_more, name='load_more'),
                  path('rates/update/', views.update_rates, name='update_rates'),
                  path('rates/download/', views.download_file, name='download'),

                  path('search/', views.search_field, name='search_field'),

                  path('news/', views.news, name='news'),
                  path('news/<int:page>/', views.news, name='root_paginate'),
                  path('news/update/', views.update_news, name='update_news'),

                  path('watchlist/', views.watchlist, name='watchlist'),
                  path('watchlist/download/', views.download_file_watchlist, name='download_watchlist'),

                  path('user-dropdown/', views.user_dropdown, name='user-dropdown'),

                  path('rates/price-filter/ascend', views.Filter.filter_by_price_ascend,
                       name='filter_by_price_ascend'),
                  path('rates/price-filter/descend', views.Filter.filter_by_price_descend,
                       name='filter_by_price_descend'),
                  path('rates/change1h-filter/ascend', views.Filter.filter_by_change1h_ascend,
                       name='filter_by_change1h_ascend'),
                  path('rates/change1h-filter/descend', views.Filter.filter_by_change1h_descend,
                       name='filter_by_change1h_descend'),
                  path('rates/change24h-filter/ascend', views.Filter.filter_by_change24h_ascend,
                       name='filter_by_change24h_ascend'),
                  path('rates/change24h-filter/descend', views.Filter.filter_by_change24h_descend,
                       name='filter_by_change24h_descend'),
                  path('rates/change7d-filter/ascend', views.Filter.filter_by_change7d_ascend,
                       name='filter_by_change7d_ascend'),
                  path('rates/change7d-filter/descend', views.Filter.filter_by_change7d_descend,
                       name='filter_by_change7d_descend'),
                  path('rates/supply-filter/ascend', views.Filter.filter_by_supply_ascend,
                       name='filter_by_supply_ascend'),
                  path('rates/supply-filter/descend', views.Filter.filter_by_supply_descend,
                       name='filter_by_supply_descend'),
                  path('rates/id-filter/ascend', views.Filter.filter_by_id_ascend,
                       name='filter_by_id_ascend'),
                  path('rates/id-filter/descend', views.Filter.filter_by_id_descend,
                       name='filter_by_id_descend'),
                  path('rates/name-filter/ascend', views.Filter.filter_by_name_ascend,
                       name='filter_by_name_ascend'),
                  path('rates/name-filter/descend', views.Filter.filter_by_name_descend,
                       name='filter_by_name_descend'),
                  path('rates/symbol-filter/ascend', views.Filter.filter_by_symbol_ascend,
                       name='filter_by_symbol_ascend'),
                  path('rates/symbol-filter/descend', views.Filter.filter_by_symbol_descend,
                       name='filter_by_symbol_descend'),
                  path('rates/coin_id-filter/ascend', views.Filter.filter_by_coin_id_ascend,
                       name='filter_by_coin_id_ascend'),
                  path('rates/coin_id-filter/descend', views.Filter.filter_by_coin_id_descend,
                       name='filter_by_coin_id_descend'),

                  path('watchlist/price-filter/ascend', views.FilterWatchlist.filter_by_price_ascend,
                       name='watchlist_filter_by_price_ascend'),
                  path('watchlist/price-filter/descend', views.FilterWatchlist.filter_by_price_descend,
                       name='watchlist_filter_by_price_descend'),
                  path('watchlist/change1h-filter/ascend', views.FilterWatchlist.filter_by_change1h_ascend,
                       name='watchlist_filter_by_change1h_ascend'),
                  path('watchlist/change1h-filter/descend', views.FilterWatchlist.filter_by_change1h_descend,
                       name='watchlist_filter_by_change1h_descend'),
                  path('watchlist/change24h-filter/ascend', views.FilterWatchlist.filter_by_change24h_ascend,
                       name='watchlist_filter_by_change24h_ascend'),
                  path('watchlist/change24h-filter/descend', views.FilterWatchlist.filter_by_change24h_descend,
                       name='watchlist_filter_by_change24h_descend'),
                  path('watchlist/change7d-filter/ascend', views.FilterWatchlist.filter_by_change7d_ascend,
                       name='watchlist_filter_by_change7d_ascend'),
                  path('watchlist/change7d-filter/descend', views.FilterWatchlist.filter_by_change7d_descend,
                       name='watchlist_filter_by_change7d_descend'),
                  path('watchlist/supply-filter/ascend', views.FilterWatchlist.filter_by_supply_ascend,
                       name='watchlist_filter_by_supply_ascend'),
                  path('watchlist/supply-filter/descend', views.FilterWatchlist.filter_by_supply_descend,
                       name='watchlist_filter_by_supply_descend'),
                  path('watchlist/id-filter/ascend', views.FilterWatchlist.filter_by_id_ascend,
                       name='watchlist_filter_by_id_ascend'),
                  path('watchlist/id-filter/descend', views.FilterWatchlist.filter_by_id_descend,
                       name='watchlist_filter_by_id_descend'),
                  path('watchlist/name-filter/ascend', views.FilterWatchlist.filter_by_name_ascend,
                       name='watchlist_filter_by_name_ascend'),
                  path('watchlist/name-filter/descend', views.FilterWatchlist.filter_by_name_descend,
                       name='watchlist_filter_by_name_descend'),
                  path('watchlist/symbol-filter/ascend', views.FilterWatchlist.filter_by_symbol_ascend,
                       name='watchlist_filter_by_symbol_ascend'),
                  path('watchlist/symbol-filter/descend', views.FilterWatchlist.filter_by_symbol_descend,
                       name='watchlist_filter_by_symbol_descend'),
                  path('watchlist/coin_id-filter/ascend', views.FilterWatchlist.filter_by_coin_id_ascend,
                       name='watchlist_filter_by_coin_id_ascend'),
                  path('watchlist/coin_id-filter/descend', views.FilterWatchlist.filter_by_coin_id_descend,
                       name='watchlist_filter_by_coin_id_descend'),
              ] + static(settings.STATIC_URL)

