# Generated by Django 4.2.1 on 2023-05-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crypto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coin_id", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                ("percent_change_1h", models.CharField(max_length=100)),
                ("percent_change_24h", models.CharField(max_length=100)),
                ("percent_change_7d", models.CharField(max_length=100)),
                ("circulating_supply", models.CharField(max_length=100)),
                ("watchlist", models.BooleanField(default=False)),
            ],
        ),
    ]
