# Generated by Django 4.2.1 on 2023-05-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cryptocurrency",
            "0002_alter_crypto_circulating_supply_alter_crypto_coin_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="crypto",
            name="circulating_supply",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="crypto",
            name="percent_change_1h",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="crypto",
            name="percent_change_24h",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="crypto",
            name="percent_change_7d",
            field=models.BigIntegerField(),
        ),
    ]
