# Generated by Django 4.2.1 on 2023-05-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cryptocurrency", "0003_alter_crypto_circulating_supply_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crypto",
            name="circulating_supply",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="crypto",
            name="percent_change_1h",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="crypto",
            name="percent_change_24h",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="crypto",
            name="percent_change_7d",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="crypto",
            name="price",
            field=models.FloatField(),
        ),
    ]
