# Generated by Django 4.2.1 on 2023-05-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cryptocurrency", "0004_alter_crypto_circulating_supply_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crypto",
            name="circulating_supply",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="crypto",
            name="coin_id",
            field=models.BigIntegerField(unique=True),
        ),
    ]
