# Generated by Django 4.2.1 on 2023-05-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cryptocurrency", "0005_alter_crypto_circulating_supply_alter_crypto_coin_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("text", models.TextField()),
                ("date", models.CharField()),
                ("source", models.CharField()),
                ("link", models.TextField()),
            ],
        ),
    ]
