# Generated by Django 4.2.1 on 2023-06-06 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cryptocurrency", "0009_alter_crypto_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crypto",
            name="watchlist",
        ),
    ]
